---
title: "TrafficBDE"
author: "Aikaterini Chatzopoulou, Kleanthis Koupidis, Charalampos Bratsas"
date: "26 Ιουλίου 2017"
output: html_document
---

# Intoduction

This package was created in order to enable the creation of a neural network model, for the needs of a European project. “TrafficBDE” includes functions for properly formulating the data, training the neural network and predicted the wanted variable. This document introduces you to TrafficBDE's basic set of tools.

The user should use only the `kStepsForward` function.

## Input

The input dataset of the main function is an excel file. There are different parameters that a user could specify and interact with the results. The parameters: “steps”, “predict” and “Link_id” should be defined by the user, to form the dataset. Then an automated process formulates the data in order to provide the prediction of the wanted variable for the desired time and road.

+-------------+--------------------------------------------------------------------------------------------+
| Input       | Description                                                                                |
+=============+============================================================================================+
| steps       | How many steps forward the prediction will be                                              |
+-------------+--------------------------------------------------------------------------------------------+
| Link_id     | The Link_id of the road                                                                    |
+-------------+--------------------------------------------------------------------------------------------+
| dimension   | The dimension of the road                                                                  |
+-------------+--------------------------------------------------------------------------------------------+
| datetime    | The date time for the pediction. The format of the datetime should be '%Y-%m-%d %H:%M:%S'  |
+-------------+--------------------------------------------------------------------------------------------+
| predict     | The argument to be predicted                                                               |
+-------------+--------------------------------------------------------------------------------------------+

Table: A sort description about the inputs. 

## Output
The output of this process is a matrix with the predicted and real values and the RMSE. The rows are equal to the steps.

## Examples
Simple examples the `kStepsForward` function are provided, in order for the user to understand the use and how to deal with these function.

The sample of the dataset that is being used is available in TrafficBDE package and represents the traffic fload of the road with Link_id: "163204843", for January 2017.

The first example provides, in one step, the prediction of the Mean speed at 14.00 on 27 Jan. 2017
`kStepsForward(1, "163204843", "1", "2017-01-27 14:00:00", "Mean_speed")`

The second example provides, in one step, the prediction of the Entries at 20.00 on 15 Jan. 2017
`kStepsForward(1, "163204843", "1", "2017-01-15 20:00:00", "Entries")`
